### ISSUE TITLE
Usage with status bar

### ISSUE THREAD

**Issue by ugrdursun** [WrathChaos/react-native-header-view#10]
Hello,

I am having this issue (both normal iphone and iphone x family)

![image](https://user-images.githubusercontent.com/23141977/76958010-f13a6b00-6927-11ea-8e80-e9d67c90e5cf.png)

I am having this at all 3 headers and just found the solution by myself adding this prop:

`containerStyle={{marginTop: getStatusBarHeight()}}`

But as per introduction Everything seems nice and happening automatically, what did i miss ?

**Comment by kuraydev** [comment]
Hello @ugrdursun,
`RNHeaderView` should handle this itself,  can you share with me the usage of the `RNHeaderView`?

**Comment by ugrdursun** [comment]
> Hello @ugrdursun,
> `RNHeaderView` should handle this itself, can you share with me the usage of the `RNHeaderView`?

I just copied the same codes of introduction to a blank page. 
```

class Groups extends React.Component {

    render () {

        return(
            <View style={{styles.container}}>
                        <AppleHeader
                        containerStyle={{marginTop: getStatusBarHeight()}} //commenting this line causes the problem
                        largeTitle={'Gruplar ve Arkadaşlar'}
                        dateTitle={'Arkadaşların burda çıkar'}
                        StatusBar={true} //this line does nothing by the way
/>
                        
                          
            </View>
        )

    }

}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor:'#ffffff'
      
    },
})

```

**Comment by kuraydev** [comment]
First of all, your container style is wrong. It should be:
```jsx
<View style={styles.container}>

</View>
```

Secondly, please delete `View` container and it should work. `AppleHeader` should handle itself :)

**Comment by kuraydev** [comment]
Here is the example of your usage :) 
https://github.com/WrathChaos/RN-HeaderView-Example

**Comment by ugrdursun** [comment]
> First of all, your container style is wrong. It should be:
> 
> ```js-jsx
> <View style={styles.container}>
> 
> </View>
> ```
> 
> Secondly, please delete `View` container and it should work. `AppleHeader` should handle itself :)

The first thing was all a copy paste mistake, sorry for that its of course not "{{}}" otherwise react would throw an error :)

Thanks for your example, I think problem is using it with **View** like you said, **SafeAreaView** fixes that!

Thanks for your assist

**Comment by kuraydev** [comment]
Have fun :) 
Feel free to open an issue if you have problem or idea to improve this library :)
