### ISSUE TITLE
Is there any way this is compatable with expo?

### ISSUE THREAD

**Issue by wildaces215** [WrathChaos/react-native-header-view#11]
I am currently creating an app with react native and expo and have the following error
![image](https://user-images.githubusercontent.com/13178401/77479664-98227980-6df6-11ea-9f85-8be53eb8f713.png)

**Comment by kuraydev** [comment]
I need to test it first but of course, I believe that I can do it :) I will inform you ASAP

**Comment by kuraydev** [comment]
Hello again @wildaces215,
Here is the new example for Expo: https://github.com/WrathChaos/react-native-header-view/tree/expo

Also, you need to use 
```
npm i WrathChaos/react-native-dynamic-vector-icons#expo
```
Expo version of react native dynamic vector icons. After that, it should work :)

**Comment by wildaces215** [comment]
Thanks!
