### ISSUE TITLE
Device Notch Support

### ISSUE THREAD

**Issue by HasanSahabGlobal** [WrathChaos/react-native-header-view#15]
It is an amazing header but I think that you should be adding support to the device notch, please!

**Comment by kuraydev** [comment]
Hello @HasanSahabGlobal,
Which header component are we talking about? I think all of them has notch support if it is not you should use SafeAreaView to handle it. However, I can handle it on a built-in side but I need to test it. 

Can you also provide me a screenshot?

**Comment by HasanSahabGlobal** [comment]
Hello @WrathChaos,
yes, i know i can use SafeArea but it is not good.
i think, it is better if you handle it from component.
like AppBar in react-native-paper.

I will provide you with some screen shoots later.
thanks!

**Comment by kuraydev** [comment]
> Hello @WrathChaos,
> yes, i know i can use SafeArea but it is not good.
> i think, it is better if you handle it from component.
> like AppBar in react-native-paper.
> 
> I will provide you with some screen shoots later.
> thanks!

Waiting for the screenshots because I'm using all of these headers and all of them are already handled on notch side.
