### ISSUE TITLE
Error: 'This package itself specifies a 'main' module field that could not be resolved'

### ISSUE THREAD

**Issue by prateekpareekvyas** [WrathChaos/react-native-header-view#18]

**Comment by WrathChaos** [comment]
Hello @prateekpareekvyas 
In order to use this library you need to install all of the inside libraries as well: 
```
* react-native-gorgeous-header
* react-native-classic-header
* react-native-modern-header
* react-native-apple-header
* react-native-profile-header
```

If you did, can you please share with me a reproducible example?

**Comment by prateekpareekvyas** [comment]
got the point I have to use react-native-gorgeous-header library so I have only installed this one not all

**Comment by WrathChaos** [comment]
Yes these are all separated libraries, you can use each of them individually :)
