### ISSUE TITLE
Request to Add product in Start React

### ISSUE THREAD

**Issue by maheshwari-1153** [WrathChaos/react-native-header-view#5]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start React](https://startreact.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. 

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by kuraydev** [comment]
Hello @maheshwari-1153,
I would love to be a part of Start React project. I've added the MIT License. Please let me know when the project is on the showcase :)
