### ISSUE TITLE
Apple header Bg colour options 

### ISSUE THREAD

**Issue by Srini-B** [WrathChaos/react-native-header-view#6]
Is there is a way to change background colour and text colour for Apple header. Need to set dark mode.

**Comment by kuraydev** [comment]
Hello @Srini-B,
I'm glad that you're using this lib :)

`<AppleHeader backgroundColor="black" />`

Have you tried something like that? AppleHeader itself does not cover whole header therefore, you also need to set the same background colour on its container. Here is the example;

`
      <SafeAreaView style={{ backgroundColor: "gray" }} >
        <AppleHeader backgroundColor="gray" />
      </SafeAreaView>
`

If you still could not get the result which you want, please tell me and I can make an enhancement. 

Also, please share with me when your project is completed :) I would love to share it on the README :)

**Comment by Srini-B** [comment]
setting the background works, but the border-bottom color and text color remains the same, provide the textStyle like in modern header. 

would definitely share the details when the project is live :-)

**Comment by kuraydev** [comment]
I'm gonna make a prop for completely customizable style :) I will make it ASAP.

**Comment by kuraydev** [comment]
@Srini-B Hey hey :)
I've updated the library. Please check this release out. 

Now, you can completely customize the AppleHeader and amazing news. The library's size massively reduced to 7.4 kb 😱

# [Release: 0.4.7  🎉 ](https://github.com/WrathChaos/react-native-header-view/releases/tag/0.4.7)

**Comment by kuraydev** [comment]
I just closed the issue, if you have a problem please re-open it :) I will fix it ASAP. Also, waiting for your amazing project soon 🤤
