### ISSUE TITLE
Getting unable to resolve "react-native-dynamic-vector-icons"

### ISSUE THREAD

**Issue by wmortume** [WrathChaos/react-native-header-view#7]
I'm running on expo and getting this error `Unable to resolve "react-native-dynamic-vector-icons" from "node_modules\@freakycoder\react-native-header-view\lib\src\components\ClassicHeader\ClassicHeader.js"`.

**Comment by kuraydev** [comment]
Hello @clu7ch3r,
Did you install `react-native-dynamic-vector-icons`?

**Comment by wmortume** [comment]
@WrathChaos With it installed, I'm getting `Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules\react-native-dynamic-vector-icons\lib\components\Icon.tsx"`.
![image](https://user-images.githubusercontent.com/36937310/69720484-f1d89880-10cf-11ea-812c-2baa55d51702.png)
This is my package.json file
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@freakycoder/react-native-header-view": "^0.4.13",
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "expo": "^35.0.1",
    "expo-constants": "^7.0.1",
    "expo-font": "~7.0.0",
    "expo-image-picker": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "firebase": "^7.4.0",
    "formik": "^2.0.4",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-dynamic-vector-icons": "^0.2.1",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-gifted-chat": "^0.11.3",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-material-kit": "^0.5.1",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-paper": "^3.2.1",
    "react-native-progress": "^4.0.2",
    "react-native-reanimated": "~1.2.0",
    "react-native-tags-input": "^1.0.5",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "util": "^0.12.1",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "babel-preset-expo": "^7.1.0",
    "eslint": "^6.6.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.5.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-hooks": "^1.7.0"
  },
  "private": true
}
```

**Comment by kuraydev** [comment]
@clu7ch3r Can you uninstall `@expo/vector-icons`? Probably there is a conflict between vector-icons to @expo one.

**Comment by wmortume** [comment]
@WrathChaos It's still giving me the same error with it uninstalled.

**Comment by kuraydev** [comment]
@clu7ch3r I've never tried it with Expo Project. Let me test it now.

**Comment by kuraydev** [comment]
@clu7ch3r I tried and got the issue. @expo/vector-icons does not use `react-native-vector-icons` latest versions. If you check the react-native-vector-icons repo, there is a new icon bundle which named Fontisto. You have two options right now, simply fork the @expo/vector-icons and add the Fontisto and use it with it (Do not forget to open a PR for them) or you can eject from Expo (Which I recommend you, Expo sucks) and use it whatever you want withou any limit.

**Comment by kuraydev** [comment]
I've opened an issue you can follow up here: [@expo/vector-icons issue](https://github.com/expo/vector-icons/issues/112)
