### ISSUE TITLE
Add textColor prop

### ISSUE THREAD

**Issue by nullxx** [WrathChaos/react-native-header-view#8]
Recomend to implement to master textColor.
`<AppleHeader
            largeTitle={"Title"}
            textColor={textColor}
            dateTitle={"Subtitle"}
            imageSource={{
              uri: "",
            }}
          />`
Code modified: https://iwlxpfg4lg.htmlshare.cloud/

**Comment by kuraydev** [comment]
Hello @nullxx 
It has already a textColor prop. Just not the same naming. Please check this configuration README.
https://github.com/WrathChaos/react-native-header-view#apple-header-props

You can find the textColor props in there :)
